<div class="mt-3">
    <form class="d-flex w-50" method="POST">
        <input class="form-control" name="search" type="search" placeholder="Enter product name" aria-label="Search">
        <button class="btn btn-primary mx-3" type="submit">Search</button>
    </form>
</div>
<table class="table table-hover shadow mt-4">
    <thead class="bg-dark text-light">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col">Stock</th>
            <th scope="col">Additional Info</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($products as $product) {
            echo '<tr>
                    <th scope="row">' . $product->name . '</th>
                    <td>' . $product->category . '</td>
                    <td>' . $product->price . '</td>
                    <td>' . $product->stock . '</td>
                    <td>
                        <button type="button" class="btn btn-sm btn-info" id="abc" data-bs-toggle="modal" value="'.$product->_id.'" data-bs-target="#exampleModal">
                        View info
                        </button>
                    </td>
                    <td>
                        <a href="/product/update/' . $product->_id . '" class="btn btn-sm btn-warning">Edit</a>
                        <a href="/product/delete/' . $product->_id . '" class="btn btn-sm btn-danger">Delete</a>
                    </td>
                </tr>';
        }
        ?>

    </tbody>
</table>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Product</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <h6 class="text-primary">Metas</h6>
        <div id="model-meta-info">
            
        </div>
        <h6 class="text-primary">Variations:</h6>
        <div id="model-variation-info">
            
        </div>
      </div>
    </div>
  </div>
</div>