<div class="text-center container">
    <main class="form-signin w-25 m-auto">
        <?php echo $this->tag->form(''); ?>
        <h1 class="h3 mb-3 fw-normal">Update</h1>
        <div class="form-floating mt-3">
            <?php
            echo $this->tag->textField(
                [
                    "name",
                    'value' => $users->name,
                    'class' => 'form-control'
                ]
            );
            ?>
            <label for="name">Full Name</label>
        </div>
        <div class="form-floating mt-3">
            <?php
            echo $this->tag->emailField(
                [
                    "email",
                    'value' => $users->email,
                    'class' => 'form-control'
                ]
            );
            ?>
            <label for="email">E-Mail</label>
        </div>
        <div class="form-floating mt-3">
            <?php
            echo $this->tag->textField(
                [
                    "username",
                    'value' => $users->username,
                    'class' => 'form-control'
                ]
            );
            ?>
            <label for="username">User name</label>
        </div>
        <?php
        echo $this->tag->submitButton(
            [
                "Update",
                'class' => 'w-100 btn btn-lg btn-primary mt-3'
            ]
        );
        ?>
        </form>
    </main>
</div>
<div class="alert alert-success w-50 m-auto">uid : <?php if (isset($message))printf("Updated %d document(s)\n", $message); ?></div>
