<div class="container w-75 m-auto shadow mt-3 pb-4">
    <h1 class="text-center text-primary">Add Order</h1>
    <form class="" method="POST">
        <div class="row">
            <div class="col">
                <label for="name">Select Product</label>
                <select name="product-id" id="product-info" class="form-select" aria-label="Default select example">
                    <option val=""></option>
                    
                    <?php
                        foreach($products as $product) {
                            echo '<option value="'.$product->_id.'">'.$product->name.'</option>';
                        }
                    ?>
                </select>
            </div>
            <div class="col">
                <label for="name">Select Variation of the product</label>
                <select class="form-select" class="product-variation" aria-label="Default select example">
                    <option val=""></option>
                    <option value="1">One</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-floating mt-3">
                    <input type="text" class="form-control" name="customer-name" placeholder="Name">
                    <label for="name">Customer Name</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mt-3">
                    <input type="text" class="form-control" name="quantity" placeholder="Name">
                    <label for="quantity">Quantity</label>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Add Order</button>
    </form>
</div>